GEN-2161: new design - Buttons
HedvigInsurance/ugglan pull request #1379
Opened 2024-06-18 12:23 UTC by sladan-hedvig

## [APP-XXX]

- Updated buttons

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2024-06-18 14:13 UTC, julia-andersson requested changes

2024-06-18 14:13 UTC, julia-andersson commented on Projects/hCoreUI/Sources/hButton/hButton.swift
> +    @Environment(\.hUseNewDesign) var hUseNewDesign
can we remove this?

2024-06-18 14:13 UTC, julia-andersson commented on Projects/hCoreUI/Sources/hButton/hButton.swift
> +            .buttonSizeModifier(size, useNewDesing: hUseNewDesign)
remove new design

2024-06-19 10:59 UTC, julia-andersson commented
You could also just merge radio option branch to get rid of that hUseNewDesign

2024-06-19 11:43 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hButton/hButton.swift
> +            .buttonSizeModifier(size, useNewDesing: hUseNewDesign)
Removed!

2024-06-19 11:43 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hButton/hButton.swift
> +    @Environment(\.hUseNewDesign) var hUseNewDesign
removed new design!

2024-06-20 09:51 UTC, julia-andersson approved these changes

2024-06-24 07:09 UTC, merged