Addons UI
HedvigInsurance/ugglan pull request #1615
Opened 2024-11-25 08:56 UTC by juliaendre

## [APP-XXX]

- Added Addons as a new module
- Added design according to this [Figma](https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=2765-167390&node-type=canvas&t=5WsfPuZG8vJy81Ar-0)

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2024-11-27 11:05 UTC, sladan-hedvig commented on Projects/Home/Sources/Models/QuickAction.swift
> +            return "Edit addon"
I guess its fine until we have an entry point(s)

2024-11-27 11:06 UTC, sladan-hedvig commented on Projects/hCore/Sources/Models/EditType.swift
> +        case .addon: return "Addon"
I guess its fine until we decide on entry point(s)

2024-11-27 14:13 UTC, juliaendre commented on Projects/Addons/Sources/Views/ChangeAddonScreen.swift
> +                    placeHolder: "Välj skydd"
@sladan-hedvig are you referring to "Välj skydd"? why do we want it there?

2024-11-27 15:51 UTC, juliaendre commented on Projects/Addons/Sources/Views/ChangeAddonSummaryScreen.swift
> +            total: .init(amount: "220", currency: "SEK")
I guess we will get this from backend

2024-12-02 12:42 UTC, sladan-hedvig requested changes

2024-12-02 12:54 UTC, sladan-hedvig approved these changes

2024-12-02 12:58 UTC, merged