Rremove store loading contracts
HedvigInsurance/ugglan pull request #1620
Opened 2024-11-28 10:48 UTC by juliaendre

## [APP-XXX]

- Not sure if this is anything we want but I thought it would be nice to remove `LoadingStoreViewWithContent` and only have it for state

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2024-11-28 15:19 UTC, sladan-hedvig requested changes
Ok, lets remove it. Have some small things that needs to be reviewed 👍

2024-11-28 15:19 UTC, sladan-hedvig commented on Projects/Contracts/Sources/View/ContractTable.swift
> +            successView.loading($vm.viewState, showLoading: false)
Instead of specifiang showLoading, use 
.loadingButtonWithErrorHandling - this one show the same view for success and loading

2024-11-28 15:19 UTC, sladan-hedvig commented on Projects/Contracts/Sources/View/ContractTable.swift
> +        actionCancellable = store.actionSignal
I think you dont need actionCancellable and following that actionSignal.
Only having this should work
```
        loadingCancellable = store.loadingSignal
            .receive(on: RunLoop.main)
            .sink { _ in
            } receiveValue: { [weak self] action in
                let getAction = action.first(where: { $0.key == .fetchContracts })
                switch getAction?.value {
                case let .error(errorMessage):
                    self?.viewState = .error(errorMessage: errorMessage)
                case .loading:
                    self?.viewState = .loading
                default:
                    self?.viewState = .success
                }
            }
```

2024-11-28 15:19 UTC, sladan-hedvig commented on Projects/Payment/Sources/Screens/PaymentsView.swift
> +        actionCancellable = store.actionSignal
Same as mentioned in another places

2024-11-29 08:32 UTC, juliaendre commented on Projects/Payment/Sources/PaymentStore.swift
> -            removeLoading(for: .getHistory)
Oh yes we want it, removed by accident

2024-11-29 08:57 UTC, sladan-hedvig reviewed
Can we have those small things in place? After that we can merge ⭐

2024-11-29 08:57 UTC, sladan-hedvig commented on Projects/Contracts/Sources/View/ContractTable.swift
> +            successView.loading($vm.viewState)
We don't need both: 
loading
loadingWithButtonLoading
just loadingWithButtonLoading here

2024-11-29 08:57 UTC, sladan-hedvig commented on Projects/Payment/Sources/Screens/PaymentsView.swift
> +            .loadingWithButtonLoading($vm.viewState)
We don't need both:
loading
loadingWithButtonLoading
just loadingWithButtonLoading here

2024-11-29 10:51 UTC, sladan-hedvig approved these changes
⭐

2024-11-29 11:18 UTC, merged