APP-519-show-toast-on-copy
HedvigInsurance/ugglan pull request #589
Opened 2022-06-28 12:47 UTC by tarikstafford

## [APP-519]

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2022-06-29 10:06 UTC, SatishBV approved these changes

2022-07-04 07:12 UTC, sampettersson requested changes

2022-08-12 05:10 UTC, tarikstafford commented on Projects/Forever/Sources/DiscountCodeSection.swift
>                          innerBag += self.service.dataSignal.atOnce()
updated

2022-08-23 08:01 UTC, sampettersson approved these changes

2022-08-23 08:02 UTC, merged