Move cross sells to octopus
HedvigInsurance/ugglan pull request #732
Opened 2023-04-24 16:32 UTC by sladan-hedvig

## CLX-539

- Migrated get cross sales to octopus
- Added support for multiple cross sales infos
- Not showing all cross sales infos (We will add that later on)

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2023-04-24 19:26 UTC, sladan-hedvig commented
FAQ are not ready. They are having some issues on promise cms.

2023-04-26 12:55 UTC, julia-andersson requested changes

2023-04-26 12:55 UTC, julia-andersson commented on Projects/Contracts/Sources/View/CrossSellingStack.swift
> +                //                    .filter { crossSell in
remove comments

2023-04-28 07:51 UTC, sladan-hedvig commented on Projects/Contracts/Sources/View/CrossSellingStack.swift
> +                //                    .filter { crossSell in
Removed! :) tack

2023-04-28 08:47 UTC, merged