Feature/claims navigation/add new damage picker screen
HedvigInsurance/ugglan pull request #814
Opened 2023-06-15 07:44 UTC by juliaendre

## [APP-XXX]

- Location picker screen
- Damage picker screen
- Brand/model picker screen
- Created generic checkbox picker

Figma: https://www.figma.com/file/QdEYhDOuTTci4AUCldDvqt/Navigation?type=design&node-id=695-11837&t=7S9g4e4uSRxARVA5-0

## Checklist

- [x] Dark/light mode verification
- [x] Landscape verification
- [x] iPad verification
- [x] iPod/iPhone 12 mini/iPhone SE verification

2023-06-16 12:56 UTC, sladan-hedvig requested changes

2023-06-16 12:56 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hForm/hRow.swift
> +    public func withoutDivider() -> Self {
Ditch this, better use enivorment property

2023-06-16 12:56 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hForm/hRow.swift
> +    var showDivider: Bool = true
Better switch this to environment property and create modifier to set it to disable but default value should be true.
Later on, you can put that modifier on hSection level and all hRow inside section with inherit that modifier.

2023-06-16 12:56 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hForm/hRow.swift
> +public struct StandaloneChevronNewAccessory: View {
Merge this with StandaloneChevronAccessory
and add environment hUseNewDesign property to decide if you want to use it.

2023-06-16 12:56 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hForm/hRow.swift
> +            .foregroundColor(hLabelColorNew.tertiary)
Remove foregroundColor. This should be on decided on where it was called upon

2023-06-16 12:56 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hForm/hRow.swift
> +    public var withNewChevronAccessory: hRow<Content, ChevronNewAccessory> {
I think you can ditch this after you merge ChevronNewAccessory and ChevronAccessory

2023-06-16 12:56 UTC, sladan-hedvig commented on Projects/hCoreUI/Sources/hForm/hRow.swift
> +        hRow<Content, ChevronNewAccessory>(ChevronNewAccessory()) {
Also this

2023-06-19 09:06 UTC, julia-andersson commented on Projects/Claims/Sources/Views/SubmitClaim/SingleItem/CheckboxPickerScreen.swift
> +    let smallerPadding: Bool?
@sladan-hedvig but that is not the same thing?

2023-06-19 09:32 UTC, sladan-hedvig approved these changes

2023-06-19 10:02 UTC, merged