Feature/blured background on detend
HedvigInsurance/ugglan pull request #833
Opened 2023-06-22 07:39 UTC by sladan-hedvig

- Added blured background as option for detent

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2023-06-22 07:42 UTC, sladan-hedvig commented
Just add .bluredBackground as option on journeys

2023-06-22 14:55 UTC, juliaendre commented
Should the background not be more blurred?

2023-06-26 09:00 UTC, julia-andersson requested changes

2023-06-26 09:00 UTC, julia-andersson commented on Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
> +            if #available(iOS 15.0, *), options.contains(.bluredBackground) {
just a typo: should be .blurredBackground

2023-06-26 09:00 UTC, julia-andersson commented on Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
> +                    useBlur: options.contains(.bluredBackground)
same

2023-06-26 09:00 UTC, julia-andersson commented on Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
> +        if #available(iOS 16.0, *), options.contains(.bluredBackground) {
same

2023-06-26 09:00 UTC, julia-andersson commented on Projects/hCoreUI/Sources/PresentationStyle+Detented.swift
> +    public static let bluredBackground = PresentationOptions()
blurredBackground

2023-06-26 09:15 UTC, sladan-hedvig commented
> Should the background not be more blurred?

I am not sure xD this is regular blur in iOS

2023-06-26 09:32 UTC, julia-andersson approved these changes

2023-06-26 09:35 UTC, merged