GEN-1107-claims-navigation-pests-UI
HedvigInsurance/ugglan pull request #974
Opened 2023-09-12 13:45 UTC by julia-andersson

## [GEN-1107]

- Claims navigation pests UI

## Checklist

- [ ] Dark/light mode verification
- [ ] Landscape verification
- [ ] iPad verification
- [ ] iPod/iPhone 12 mini/iPhone SE verification

2023-09-14 12:30 UTC, sladan-hedvig commented
Missing action for info button. I guess it will be the same as on glass

2023-09-14 12:32 UTC, sladan-hedvig requested changes
Just need to set that info action

2023-09-14 13:36 UTC, julia-andersson commented
Skipping info button for now

2023-09-15 09:48 UTC, sladan-hedvig commented
Did some small changes :) otherwise looks good 👍

2023-09-15 09:48 UTC, sladan-hedvig approved these changes

2023-09-15 11:22 UTC, merged